import moment from 'moment';
import Utils from '../utils/common';

export default {
  accounts: [
    [
      1,
      222010772,
      moment(),
      1,
      'savings',
      'active',
      20000.95,
    ],
    [
      2,
      222010872,
      moment(),
      3,
      'current',
      'dormant',
      400000.95,
    ],
  ],
  users: [
    [
      'tejumoladavid@gmail.com',
      'David',
      'Tejumola',
      Utils.hashPassword('password'),
      'staff',
      true,
    ],
    [
      'johnoke@gmail.com',
      'John',
      'Oke',
      Utils.hashPassword('password'),
      'staff',
      false,
    ],
    [
      'boladeojo@gmail.com',
      'Bolade',
      'Ojo',
      Utils.hashPassword('password'),
      'client',
      false,
    ],
    [
      'sholaadeola@gmail.com',
      'Shola',
      'Adeola',
      Utils.hashPassword('password'),
      'client',
      false,
    ],
  ],
  transactions: [
    [
      222010772,
      1,
      'debit',
      '10000.00',
    ],
    [
      222010772,
      1,
      'debit',
      '10000.00',
    ],
    [
      222010772,
      1,
      'debit',
      '10000.00',
    ],
  ],
};
